name: generate pacman game

on:
schedule: # Run automatically every 24 hours
    - cron: "0 */24 * * *"
workflow_dispatch: # Allows manual triggering
push: # Runs on every push to the main branch
    branches:
    - main

jobs:
generate:
    permissions:
    contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: generate pacman-contribution-graph.svg
      uses: abozanona/pacman-contribution-graph@main
      with:
        github_user_name: ${{ github.repository_owner }}

    - name: Create output directory
      run: mkdir -p output

    - name: Move generated files
      run: |
        if [ -f "pacman-contribution-graph.svg" ]; then
          cp pacman-contribution-graph.svg output/
        fi
        if [ -f "pacman-contribution-graph-dark.svg" ]; then
          cp pacman-contribution-graph-dark.svg output/
        fi

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output/
        git commit -m "Update pacman contribution graph" || exit 0
        git push
